services:
  # -------------------------------------------------------
  # MinIO Api Server: http://0.0.0.0:{9000:-RANDOM_PORT}
  # MinIO Web UI: http://0.0.0.0:{9001:-RANDOM_PORT}
  #
  # https://docs.min.io
  # https://hub.docker.com/r/minio/minio
  # -------------------------------------------------------
  minio:
    init: true
    restart: on-failure
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: ${CONTAINER_NAME:-minio}
    ports:
      - 0:9000 # Host machine port is 9000 or randomly assigned
      - 0:9001 # Host machine port is 9001 or randomly assigned
    environment:
      MINIO_UPDATE: off # https://github.com/minio/minio/discussions/15418
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
      MINIO_ROOT_USER: dummy-user
      MINIO_ROOT_PASSWORD: dummy-password
      MINIO_REGION_NAME: us-east-1
    entrypoint: >
      sh -c "
      (while ! curl -s http://localhost:9000/minio/health/live; do sleep 1; done &&
      mc alias set minio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
      if ! mc ls minio/dummy-bucket > /dev/null 2>&1; then
        mc mb minio/dummy-bucket
      else
        echo 'Bucket dummy-bucket already exists';
      fi) &
      minio server /data
      "
    healthcheck:
      test: [CMD, curl, -f, http://localhost:9000/minio/health/live]
      interval: 10s # How often to run the health check
      timeout: 5s # Time to wait for a response
      retries: 3 # Number of retries before marking the container as unhealthy
